### ISSUE TITLE
Generating Meshes

### ISSUE THREAD

**Issue by mjs513** [michaelerule/Uno9341TFT#1]
Not an issue but a question.

Hope you are still around.  How do you generate the meshes for the models that you have in the demo.

**Comment by michaelerule** [comment]
A good question, it's been a while and it seems like this was never properly documented. It looks like the answer lies in `Uno9341TFT/examples/obsolete/bunny`. First, the meshes are simplified in MeshLab (e.g. `bunny_ultralowpoly_1.stl`). Then, one exports them to a JSON format using the MeshLab JSON Exporter. Then, the JSON is piped to the script `convert_json_to_triangles.py` which outputs the C datastructures. I've moved this code to `examples/convert_stl_to_JSON_and_C_datastructures` to try to clean this up a bit!

**Comment by michaelerule** [comment]
I've added the following notes for converting meshes: 

Meshlab can output meshes as JSON formatted triangle and vertex data. We need to convert this into the triangle format used for the Arduino3D models.


Workflow:

1. Open model in MeshLab
2. Repair and edit mesh as necessary
3. Simplify mesh, no more than 256 vertices or triangles! 
    Realistically, only models with <100 triangles will work well on the Arduino
    (suggest using MeshLab's quadratic edge collapse decimation routine)
4. Recompute vertex, face normals (if needed)
5. Export as .json data
6. Convert to C datastructures:
    `cat model.json | ./convert_json_to_triangles.py >> model.h`
7. This can compute the vertices, faces, edges, face normals, and vertex normals. 
    Depending on the desired rendering mode, we may not need all of this data. 
    Unnecessary data can be deleted.

**Comment by mjs513** [comment]
Wow - thanks for the quick reply.  I am just getting into trying 3D rendering using a microprocessor and wanted to give this a try.  I did give tiny-3d-engine a try but this seems to be more complete.

Also was looking at porting parts over to work Teensy (cortex-M arm processors) using a ILI9488 display.  These are a heck of a lot faster and much more memory.

Guess I have to learn how to use MeshLab now :)

Thanks again
