### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by Rob0xFF** [michaelerule/Uno9341TFT#4]
Hi,

this is neat stuff. I got it working on my Atmega2560 and it is fast. How can I set the screen rotation, there seems to be no method a.t.m.? I tried to adopt the rotation method from Adafruit_GFX and Adafruit_TFTLCD, it sets the registers, but the address window seems to be hardcoded?!

Thanks, Rob

**Comment by michaelerule** [comment]
Ah, the screen rotation I *think* might be something that got optimized out for speed: The display has a natural orientation, so that pixels delivered sequentially fill in rows. It's important to keep all the line drawing, fill, etc, commands aware of these coordinates so that they can be optimized. 

This means that any coordinate changes need to happen at a high, almost the user level. For the most part, this is a non-issue: just exchanging X and Y for all the drawing commands will do it. But! I think maybe for text rendering it could be a bit broken. I don't recall how the Adafruit GFX library handles text orientation. 

Not sure I understood the question quite correctly --- does that address it? Sadly my TFT screen broke so I no longer have a platform that allows me to test/fix things ) :

**Comment by Rob0xFF** [comment]
Hi,

the memory/screen rotation is set via the MADCTL register (0x36), where Bit  7 and 6 (MX and MY) control the read/write directions in X and Y, and Bit 5 (MV) does flip X and Y. So for landscape mode, this is what I need, one has to set Bit 5 to 1. 

From the datasheet, on page 127, there is shown, that if MV bit is set, the memory is flipped but the display is clipped right and the left part of the screen is overwritten with the clipped fraction.

So in practice I set the MADCTL register to 111x1xxx, and see the display has rotated, but the image is clipped as shown in the datasheet. This does not happen when I set the same registers but use the Adafruit library. So there must be some correction in the Adafruit lib, which has to be transferred to your lib, but I cannot find it. It might be something with the AddressWindow. Maybe someone could help?

Thanks, rob

**Comment by Rob0xFF** [comment]
Adafruit calls 

setAddrWindow(0, 0, _width - 1, _height - 1);

after setting the register, nevertheless calling the respective macro in your lib does not do the trick.

**Comment by Rob0xFF** [comment]
define SET_X_RANGE(x1,x2) {\
    COMMAND(SET_COLUMN_ADDRESS_WINDOW);\
    SEND_PAIR(0,(x1));\
    SEND_PAIR(0,(x2));\
}

This is called by the SET_WINDOW Macro. If we are in landscape mode, we need more than 8 Bit to adress the right part of the screen, so we shoud send  SEND_PAIR((x1)>>8,(x1)); and SEND_PAIR((x2)>>8,(x2));

I will give it a try tomorrow.

**Comment by michaelerule** [comment]
I see it, yes! I remember now: 

This is a sin of over-optimization. setAddrWindow was replaced by several macros: 

`SET_XY_RANGE`, `SET_XY_LOCATION`, `SET_X_LOCATION`, `SET_Y_LOCATION`, `RESET_X_RANGE`, and `ZERO_XY`

These perform subsets of the function setAddrWindow. This change was made to absolutely minimize the number of commands sent to the display. It seems a bit absurd, but for the 3D rendering it seemed to help a bit. 

In particular, avoiding extra commands to clean up/reset the address window after each drawing operating sped things up. Evidently, the way that these new macros are set up does not play nicely with transposed screen orientation. The fast drawing commands don't even use `setAddrWindow`, 

So, these matter for speed, but I'm not sure they are critical in all applications. Most of the speed improvements came from: 

 - Creating a mode to send color data where the high and the low byte of the color data are the same. These are "fast colors" as they do not require changing (possibly multiple) `PORT` states when transferring lots of color data of the same color.

- Unrolling the loops in the `flood` routine. 

This library is pretty heavily modified from Adafruit's, to support as-fast-as-possible checking of the `frame_id` bit hiding in the color data. So routines that should simply draw pixels instead swap back and forth between reading and writing quickly. Removing absolutely everything that is not-essential was needed to get this to work on the UNO. 

If you're not using the `frame_id` bit trick to reduce flicker or handle the occlusion problem for 3D rendering, then it might be expedient to simply incorporate the "fast colors" and "fast flood" into Adafruit's source code?

**Comment by Rob0xFF** [comment]
Thanks for the answer. In my case, i have a lot of sensor data to show on the screen which updates every 1 second.  Using the original Adafruit lib, updating all these values took about 700ms. So only 30% left to handle touch events and a whole lot 700ms latency (up to). I wrote a routine, which holds strings before and after each update, looks-up the pixels occupied by these stings and updates only those pixels, which actually changed. Now all values update within 25ms. I found your library and combined my routine, now the update of all values is within the range of 1ms!!! I am not sure, if my routine is really necessary, as if I understand, you also update only those pixels which actually changed, but for all routines, not only for text. 

But for now, it only works in portrait mode.

There is so much potential in your lib!

Thanks, Rob.

**Comment by Rob0xFF** [comment]
Screen rotation works now. There is a function which adopts the original adafruit version with some minor tweaks. In the macro section I have made some of them more flexible (but maybe slower). I uploaded the files to my fork section, I someone is interested.

I encountered another "problem" with drawRect(), while the vertical lines seem to render with correct color, the horizontal lines are off visibly. I temporarily use the generic drawLine() instead of drawFastHLine(), which seems to yield better results and is faster.

Cheers, Rob

**Comment by Rob0xFF** [comment]
Michael, I wonder if you could remember the usage of the FRAME_ID_BIT?! It seems to be set in color data in certain functions, but I cannot figure out its meaning.

Thanks, Rob

**Comment by michaelerule** [comment]
Added note in readme about FRAME_ID_BIT. See also [blog post](http://crawlingrobotfortress.blogspot.com/2015/12/better-3d-graphics-engine-on-arduino.html).

**Comment by michaelerule** [comment]
There probably need to be a way to disable the FRAME_ID_BIT for cases where draw-then-erase are not needed. It is dithered on alternate scanlines, so that for solid regions and vertical lines it is not noticeable. But you are right that horizontal lines will be affected. 

Would need to review the code and decide whether its best to disable FRAME_ID_BIT with a runtime or compile-time flag. Disabling it will break 3D animation, but improve color accuracy.

**Comment by michaelerule** [comment]
Are you using `drawFastHLine` or `fastestHLine`? In any case, try commenting out the lines that look like

        color &= FRAME_ID_MASK16;
        color |= (uint16_t)(mask_flag^line_flag)<< 8;

or

        uint8_t line_flag = FRAME_ID_FLAG8*(y&1);
        color &= FRAME_ID_MASK8;
        color |= mask_flag^line_flag;

I've been going back over the code and there are some issues, I think. I think the support of masked-erasing and overdraw-checking is inconsistent amongst the "fast" drawing routines. Something funny might also be happening with permuting the color bits on the Leonardo.

**Comment by michaelerule** [comment]
Latest commit adds flag `DISABLE_MASKING_AND_OVERDRAW` to `Arduino_TFTLCD.cpp` to disable masking and overdraw. This breaks all the 3D animation code, but *might* fix the color inaccuracy issues you're seeing.

**Comment by Rob0xFF** [comment]
I now use your updated Arduino_TFTLCD.cpp to my project and it work perfectly. Thanks!

**Comment by michaelerule** [comment]
Thanks Rob, glad to know it works ( :
